#! /bin/bash



case $1 in
"start"){
        for i in whu2  whu1
        do
                echo " --------启动 $i 采集flume-------"
                ssh $i "export PATH=/usr/local/hadoop-3.1.3/bin:/usr/local/hadoop-3.1.3/sbin:/usr/local/jdk1.8.0_261/bin:/home/hadoop/bin:/home/hadoop/.jenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/kafka_2.11-2.4.1/bin:/usr/local/zookeeper-3.5.7/bin:/usr/local/flume-1.9.0/bin  && nohup /usr/local/flume-1.9.0/bin/flume-ng agent --conf-file /usr/local/flume-1.9.0/job/file-flume-kafka.conf --name a1 -Dflume.root.logger=INFO,LOGFILE >/usr/local/flume-1.9.0/log1.txt 2>&1  &"
        done
};;
"stop"){
        for i in whu2 whu1
        do
                echo " --------停止 $i 采集flume-------"
                ssh $i "ps -ef | grep file-flume-kafka | grep -v grep |awk  '{print \$2}' | xargs -n1 kill -9 "
        done

};;
esac